/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import org.gradle.jvm.tasks.Jar

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.3.41"

    java

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    implementation("com.sparkjava:spark-core:2.9.1")

    implementation("com.netflix.feign:feign-core:8.18.0")

    implementation("io.github.openfeign:feign-okhttp:10.4.0")

    implementation("io.github.openfeign:feign-jackson:10.4.0")

    implementation("io.github.openfeign:feign-slf4j:10.4.0")

    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.9.9")

    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.9.9")
}

application {
    // Define the main class for the application
    mainClassName = "teamcity.interactor.app.AppKt"
}

tasks.register<Jar>("uberJar") {

    manifest {
        attributes["Main-Class"] = application.mainClassName
    }

    from(sourceSets.main.get().output)
    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    })
}

tasks.build {
    dependsOn("uberJar")
}